---
title: "Change over Time of Stability and Density"
author: "Boyana Buyuklieva"
date: "January 25, 2020"
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(substr(inputFile,1,nchar(inputFile)-4),Sys.Date(),'.html')) })
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(ggplot2)
library(ggmosaic)
library(ggalluvial)
library(reshape2)
library(dplyr)

library(knitr)
library(kableExtra)
```

```{r}
dt <- read.csv2(paste0("../__results/_derived_data/long_dt_all_years_2020-11-14.csv"), header = T, sep = ",", fileEncoding = "UTF-8-BOM")
```

```{r}
all_years <- dt %>%
  group_by(year, 
           rgn11cd, rgn11nm,
           lad11cd, lad11nm,
           rdl_psd,
           rdl_pd, rdl_m1_sp) %>%
  summarise(count = n())

#ensure year is a factor
all_years$year <- as.factor(all_years$year)
droplevels(all_years)


#subset(all_years, rdl_psd %in% c('5_V.High-Fix*2_Low','5_V.High-Fix*3_Average'))
drop <- c(which(all_years$rdl_psd == '5_V.High-Fix*2_Low'),
          which(all_years$rdl_psd == '5_V.High-Fix*3_Average'))

all_years <- all_years[-drop,]
```




```{r}
lab_colour <- read.csv2("./PSD_colour_scheme.csv", header = T, sep = ",", fileEncoding = "UTF-8-BOM")
lab_colour$HexColur <- as.character(lab_colour$HexColur)
lnd_groups <- read.csv2("./London_Group_LUT.csv", header = T, sep = ",", fileEncoding = "UTF-8-BOM")
rgn_groups <- read.csv2("./Regions_Group_LUT.csv", header = T, sep = ",", fileEncoding = "UTF-8-BOM")
cc = c( '#ff0000','#808080','#4000ff','#009499')
```


```{r}
#columns for plotting
#https://stackoverflow.com/questions/27134516/summarizing-by-subgroup-percentage-in-r
#https://stackoverflow.com/questions/26617843/aggregation-and-percentage-calculation-by-groups
```


```{r dt}
#Create percents relative to lad
count <- aggregate(cbind(LADpercent=count) ~ lad11cd + year, data = all_years, FUN = sum)
all_years <- merge(x = all_years, y = count,
           by = c('lad11cd', 'year'),
           all.x = T) 
all_years$LADpercent <- all_years$count/all_years$LADpercent*100

#Create percents relative to region
count <- aggregate(cbind(RGNpercent=count) ~ rgn11cd + year, data = all_years, FUN = sum)
all_years <- merge(x = all_years, y = count,
           by = c('rgn11cd', 'year'),
           all.x = T) 
all_years$RGNpercent <- all_years$count/all_years$RGNpercent*100

#Create percents relative to year
count <- aggregate(cbind(YRpercent=count) ~ year, data = all_years, FUN = sum)
all_years <- merge(x = all_years, y = count,
           by = 'year',
           all.x = T) 
all_years$YRpercent <- all_years$count/all_years$YRpercent*100


#rename for tidyness
all_years <- all_years %>%
  rename(
  density = rdl_pd,
  stability = rdl_m1_sp
  )
all_years <- droplevels(all_years)
```


```{r fig0}
#baseline works
flattend1 <- aggregate(  YRpercent ~ stability + rdl_psd + year , data = all_years, FUN = sum)
flattend <- aggregate(  YRpercent ~ stability + year , data = all_years, FUN = sum)



#transcince first
  ggplot(data = flattend,
       aes(x = year, stratum = stability, alluvium = YRpercent,
           y = YRpercent, label = round(YRpercent, 1)), fill = NA )+
  geom_stratum(fill = NA, colour = NA) +
  stat_stratum(geom = "errorbar") +
  geom_label(
    aes(label = ifelse(as.numeric(year) == 1, paste(as.character(round(YRpercent,1)),'%'), NA)),
    #stat = "stratum", size = 3, direction = "y", nudge_x = -.3,color = "white", fill= rep(cc,5)) +
    stat = "stratum", size = 3, direction = "y", nudge_x = -.3,color = "black") +
  geom_label(
    aes(label = ifelse(as.numeric(year) == 5, paste(as.character(round(YRpercent,1)),'%'),NA)), 
    #stat = "stratum", size = 3, direction = "y", nudge_x = .3,color = "white",  fill= rep(cc,5))+
    stat = "stratum", size = 3, direction = "y", nudge_x = .3,color = "black") +
  #flow diagrant starts here
  geom_flow(data = flattend1, aes(x = year, alluvium = rdl_psd, y = YRpercent, fill = rdl_psd), colour='white', width = 0)+
  scale_fill_manual(values = lab_colour$HexColur, name='Class Legend') +
  labs(y = "Percent of Given Class for Each Year") +
  theme_minimal()+
  theme(legend.position = "none")
```



```{r fig1}
flattend1 <- aggregate(  YRpercent ~  rdl_psd + stability+ year, data = all_years, FUN = sum)

ggplot(flattend1, aes(x = year, stratum = rdl_psd,alluvium = rdl_psd, y = YRpercent)) +
  geom_flow(aes(fill = rdl_psd), colour='black', width = 0) +
  geom_lode(fill = NA, colour = NA)+ 
  scale_fill_manual(values = lab_colour$HexColur, name='Class Legend') +
  labs(title = "Stability and Density: England and Wales") +
  theme_classic() +
  geom_stratum(fill = NA, colour = NA) +
  ggrepel::geom_text_repel(
    aes(label = ifelse(as.numeric(year) == 1, as.character(round(YRpercent,1)), NA)),
    stat = "stratum", size = 3, direction = "y", nudge_x = -.3
  ) +
  ggrepel::geom_text_repel(
    aes(label = ifelse(as.numeric(year) == 5, as.character(round(YRpercent,1)), NA)),
    stat = "stratum", size = 3, direction = "y", nudge_x = .3
  )+
  facet_wrap(~stability, ncol=2, scales="free")+ 
  theme(legend.position = "none")
```


# Here is the breakdown of the same labels, by region       
```{r fig2-1Regions, fig.height = 10.2, fig.width = 6.3}
flattend <- aggregate(  RGNpercent ~  stability + year + rgn11nm, data = all_years, FUN = sum)
flattend1 <- aggregate(  RGNpercent ~  stability + rdl_psd + year + rgn11nm, data = all_years, FUN = sum)

subset <- rgn_groups[rgn_groups$group_Region=='South-East',]$region

 ggplot(data = flattend[flattend$rgn11nm %in% subset,],
       aes(x = year, stratum = stability, alluvium = RGNpercent,
           y = RGNpercent, label = round(RGNpercent, 1)), fill = NA )+
  geom_stratum(fill = NA, colour = NA) +
  #stat_stratum(geom = "errorbar") +
  geom_text(
    aes(label = ifelse(as.numeric(year) == 1, paste(as.character(round(RGNpercent,1)),'%'), NA)),
    #stat = "stratum", size = 3, direction = "y", nudge_x = -.3,color = "white", fill= rep(cc,5)) +
    stat = "stratum", size = 2, direction = "y", nudge_x = -.3,color = "black") +
  geom_text(
    aes(label = ifelse(as.numeric(year) == 5, paste(as.character(round(RGNpercent,1)),'%'),NA)), 
    #stat = "stratum", size = 3, direction = "y", nudge_x = .3,color = "white",  fill= rep(cc,5))+
    stat = "stratum", size = 2, direction = "y", nudge_x = .3,color = "black") +
  #flow diagrant starts here
  geom_flow(data = flattend1[flattend1$rgn11nm %in% subset,], aes(x = year, alluvium = rdl_psd, y = RGNpercent, fill = rdl_psd), colour='white', width = 0)+
  facet_wrap(~rgn11nm, ncol=2)+ 
  scale_fill_manual(values = lab_colour$HexColur, name='Class Legend') +
  labs(y = "Percent of Areas Assigned to Classes Per Region in the South-East") +
  theme_minimal()+
  theme(legend.position = "none")

```

```{r fig2-2Regions, fig.height = 10.2, fig.width = 6.3}
subset <- rgn_groups[rgn_groups$group=='North-West',]$region
 ggplot(data = flattend[flattend$rgn11nm %in% subset,],
       aes(x = year, stratum = stability, alluvium = RGNpercent,
           y = RGNpercent, label = round(RGNpercent, 1)), fill = NA )+
  geom_stratum(fill = NA, colour = NA) +
  #stat_stratum(geom = "errorbar") +
  geom_text(
    aes(label = ifelse(as.numeric(year) == 1, paste(as.character(round(RGNpercent,1)),'%'), NA)),
    #stat = "stratum", size = 3, direction = "y", nudge_x = -.3,color = "white", fill= rep(cc,5)) +
    stat = "stratum", size = 2, direction = "y", nudge_x = -.3,color = "black") +
  geom_text(
    aes(label = ifelse(as.numeric(year) == 5, paste(as.character(round(RGNpercent,1)),'%'),NA)), 
    #stat = "stratum", size = 3, direction = "y", nudge_x = .3,color = "white",  fill= rep(cc,5))+
    stat = "stratum", size = 2, direction = "y", nudge_x = .3,color = "black") +
  #flow diagrant starts here
  geom_flow(data = flattend1[flattend1$rgn11nm %in% subset,], aes(x = year, alluvium = rdl_psd, y = RGNpercent, fill = rdl_psd), colour='white', width = 0)+
  facet_wrap(~rgn11nm, ncol=2)+ 
  scale_fill_manual(values = lab_colour$HexColur, name='Class Legend') +
  labs(y = "Percent of Areas Assigned to Classes Per Region in the North-West") +
  theme_minimal()+
  theme(legend.position = "none")

```


# Here is the breakdown of the same labels, by London SubRegion     

```{r dtLND}
lnd <- droplevels(all_years[all_years$rgn11nm == 'London',])
lnd <- merge(x = lnd, y = lnd_groups,
             by.x = 'lad11nm',
             by.y = 'lad11nm_LND')

#Create percents relative to subRegion
count <- aggregate(cbind(LNDSubpercent=count) ~ group_LND + year, data = lnd, FUN = sum)
lnd <- merge(x = lnd, y = count,
           by = c('group_LND','year'),
           all.x = T) 
lnd$LNDSubpercent <- lnd$count/lnd$LNDSubpercent*100
```

```{r fig3-LND, fig.height = 10.2, fig.width = 6.3}
flattend <- aggregate(  LNDSubpercent ~ stability + year + group_LND, data = lnd, FUN = sum)
flattend1 <- aggregate(  LNDSubpercent ~ stability + rdl_psd + year + group_LND, data = lnd, FUN = sum)



ggplot(data = flattend,
       aes(x = year, stratum = stability, alluvium = LNDSubpercent,
           y = LNDSubpercent, label = round(LNDSubpercent, 1)), fill = NA )+
  geom_stratum(fill = NA, colour = NA) +
  #stat_stratum(geom = "errorbar") +
  geom_text(
    aes(label = ifelse(as.numeric(year) == 1, paste(as.character(round(LNDSubpercent,1)),'%'), NA)),
    #stat = "stratum", size = 3, direction = "y", nudge_x = -.3,color = "white", fill= rep(cc,5)) +
    stat = "stratum", size = 3, direction = "y", nudge_x = -.3,color = "black") +
  geom_text(
    aes(label = ifelse(as.numeric(year) == 5, paste(as.character(round(LNDSubpercent,1)),'%'),NA)), 
    stat = "stratum", size = 3, direction = "y", nudge_x = .3,color = "black") +
  #flow diagrant starts here
  geom_flow(data = flattend1, aes(x = year, alluvium = rdl_psd, y = LNDSubpercent, fill = rdl_psd), colour='white', width = 0)+
  facet_wrap(~ group_LND, ncol=1)+ 
  scale_fill_manual(values = lab_colour$HexColur, name='Class Legend') +
  labs(y = "Percent of Areas Assigned to Classes Per London Subregion") +
  theme_minimal()+
  theme(legend.position = "none")


```


-------------------------------------------Extra

```{r potential}
#baseline works
flattend1 <- aggregate(  YRpercent ~ density + rdl_psd + year , data = all_years, FUN = sum)
flattend <- aggregate(  YRpercent ~ density + year , data = all_years, FUN = sum)
#transcince first
  ggplot(data = flattend,
       aes(x = year, stratum = density, alluvium = YRpercent,
           y = YRpercent, label = round(YRpercent, 1)), fill = NA )+
  geom_stratum(fill = NA, colour = NA) +
  stat_stratum(geom = "errorbar") +
  geom_label(
    aes(label = ifelse(as.numeric(year) == 1, paste(as.character(round(YRpercent,1)),'%'), NA)),
    #stat = "stratum", size = 3, direction = "y", nudge_x = -.3,color = "white", fill= rep(cc,5)) +
    stat = "stratum", size = 3, direction = "y", nudge_x = -.3,color = "black") +
  geom_label(
    aes(label = ifelse(as.numeric(year) == 5, paste(as.character(round(YRpercent,1)),'%'),NA)), 
    #stat = "stratum", size = 3, direction = "y", nudge_x = .3,color = "white",  fill= rep(cc,5))+
    stat = "stratum", size = 3, direction = "y", nudge_x = .3,color = "black") +
  #flow diagrant starts here
  geom_flow(data = flattend1, aes(x = year, alluvium = rdl_psd, y = YRpercent, fill = rdl_psd), colour='white', width = 0)+
  scale_fill_manual(values = lab_colour$HexColur, name='Class Legend') +
  labs(y = "Percent of Given Class for Each Year") +
  theme_minimal()+
  theme(legend.position = "none")
```

